apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "jet-external-services.fullname" . }}-init-minio
  labels:
    {{- include "jet-external-services.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
        - name: init-minio
          image: minio/mc:RELEASE.2022-04-07T21-43-27Z
          workingDir: /usr/local/etc/scripts
          command: ["/bin/sh", "./init.sh"]
          env:
            - name: MINIO_SERVER
              value: http://{{ include "jet-external-services.fullname" . }}:9000
          volumeMounts:
          - name: init-minio-scripts-volume
            mountPath: /usr/local/etc/scripts/
      restartPolicy: OnFailure
      volumes:
        - name: init-minio-scripts-volume
          configMap:
            name: {{ .Release.Name }}-configmap
            items:
              - key: minio-init.sh
                path: init.sh
  ttlSecondsAfterFinished: 60
