Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/focal64'

  # Network
  ## minio
  config.vm.network 'forwarded_port', guest: 9090, host: 19090
  config.vm.network 'forwarded_port', guest: 6389, host: 16389
  ## postgresql
  config.vm.network 'forwarded_port', guest: 5432, host: 15432

  config.vm.synced_folder '.vagrant-share/', '/home/vagrant/share', create: true

  # Disable default synced_folder
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'jet-external-services-vm'
    vb.gui = false

    vb.memory = 2048
    vb.cpus = 4
  end

  config.trigger.after [:up, :reload, :resume] do |t|
    t.name = 'Make external-services up'
    t.run_remote = { inline: 'cd /home/vagrant/jet-deployment/external-services && make up' }
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -q
    sudo apt-get install -yq \
      apt-transport-https \
      ca-certificates \
      curl \
      git \
      gnupg-agent \
      software-properties-common \
      make

    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    sudo apt-key fingerprint 0EBFCD88

    sudo add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) \
      stable"

    sudo apt-get update -q
    sudo apt-get install -y \
      docker-ce \
      docker-ce-cli \
      containerd.io

    sudo curl -fsSL "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose

    sudo groupadd docker
    sudo usermod -aG docker $USER
    sudo newgrp docker

    # timezone
    echo -e "\nexport TZ='Asia/Shanghai';\n" >> ~/.bashrc

    git clone https://github.com/Byzanteam/jet-deployment.git ~/jet-deployment

    echo "Provision DONE!!!"
  SHELL
end
